version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"  # Map port 3000 inside the container to port 5000 on your host machine
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    environment:
      - NODE_ENV=production
